server:
  port: 8081

spring:
  datasource:
    driverClassName:  com.mysql.cj.jdbc.Driver
    #?createDatabaseIfNotExist=true #collation = utf8_general_ci , charset = utf8
    url: jdbc:mysql://127.0.0.1:3306/productoperations?&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
  main:
    lazy-initialization: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 0b6357ac2fe211
    password: a32dfc664643fc
    properties.mail.transport.protocol: smtps
    properties.mail.smtps.auth: true
    properties.mail.smtps.from: 6c8eb1775d-51bd1c@inbox.mailtrap.io
    properties.mail.smtps.starttls.enable: true
    properties.mail.smtps.timeout: 8000

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    enabled: true


caborya:
  security:
    decodeSplit: ond75
    base64Secret: TXlBcHBEZWZhdWx0U2VjcmV0S2V5T2d1emhhbk9uZGVyU3ByaW5nQm9vdDIwMjAxOTkxQWxpTXVhejI5TWF5aXM=
    tokenValidity: 10800
    rememberMeTokenValidity: 28800
    tokenRegistrationAndResetPasswordExpiration: 1440

  support:
    mail: caborya@gmail.com
    baseUrl: localhost:8080

  service:
    annotationScanPackage: com
    expiredTokenDeleteCronExpression: 0 0 6 * * *

  menu:
    file: data/menu.json


